/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:
    N62C_Oids.h

Abstract:
    Contains Port specific defines
    
Revision History:
      When        What
    ----------    ----------------------------------------------
    04-22-2007    Created

Notes:

--*/

#pragma once

#ifndef _N62_OIDS__H
#define _N62_OIDS__H

#define ALLOWED_AUTO_CONFIG_FLAGS (DOT11_PHY_AUTO_CONFIG_ENABLED_FLAG | DOT11_MAC_AUTO_CONFIG_ENABLED_FLAG)

NDIS_STATUS
N62CValidateOIDCorrectness(
	PADAPTER pTargetAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_INCOMING_ASSOCIATION_DECISION(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_WPS_ENABLED(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_ADDITIONAL_IE(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_ENUM_PEER_INFO(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_AVAILABLE_CHANNEL_LIST(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_AVAILABLE_FREQUENCY_LIST(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_START_AP_REQUEST(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_DISASSOCIATE_PEER_REQUEST(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_GET_PROTOCOL_OFFLOAD(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_DOT11_ASSOCIATION_PARAMS(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_ADD_WOL_PATTERN(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_REMOVE_WOL_PATTERN(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_PARAMETERS(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_ADD_PROTOCOL_OFFLOAD(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_REMOVE_PROTOCOL_OFFLOAD(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_GEN_INTERRUPT_MODERATION(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_PM_ADD_PROTOCOL_OFFLOAD_LIST(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_RECEIVE_FILTER_CLEAR_FILTER(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_RECEIVE_FILTER_SET_FILTER(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_RECEIVE_FILTER_HARDWARE_CAPABILITIES(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

NDIS_STATUS
N62C_OID_RECEIVE_FILTER_CURRENT_CAPABILITIES(
	PADAPTER pAdapter,
	PNDIS_OID_REQUEST NdisRequest
);

#endif
