/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

    rc_ids.h

Abstract:

    Resource IDs used by the TOASTAPP sample application.

--*/

#define IDD_DEVICE_INTERFACES     1
#define IDC_DEVICE_INTERFACE_LIST 2

