#ifndef __INC_STATUSCODE_H
#define __INC_STATUSCODE_H

typedef enum _RT_STATUS{
	RT_STATUS_SUCCESS = 0,
	RT_STATUS_FAILURE,
	RT_STATUS_PENDING,
	RT_STATUS_RESOURCE,
	RT_STATUS_INVALID_CONTEXT,
	RT_STATUS_INVALID_PARAMETER,
	RT_STATUS_NOT_SUPPORT,
	RT_STATUS_OS_API_FAILED,
	RT_STATUS_BUFFER_TOO_SHORT,
	RT_STATUS_INVALID_LENGTH,
	RT_STATUS_NOT_RECOGNIZED,
	RT_STATUS_MALFORMED_PKT,
	RT_STATUS_PKT_DROP,
	RT_STATUS_MEDIA_BUSY,
	RT_STATUS_INVALID_DATA,
	RT_STATUS_INVALID_STATE,
	RT_STATUS_IO_EXCEPTION,
}RT_STATUS,*PRT_STATUS;

#define	CHECK_NULL_RETURN_STATUS(_Pointer)	\
{	\
	if(NULL == _Pointer)	\
	{	\
		RT_ASSERT(_Pointer, ("Pointer(" #_Pointer ") is NULL\n"));	\
		return RT_STATUS_INVALID_CONTEXT;	\
	}	\
}
#endif // #ifndef __INC_STATUSCODE_H
