#****************************** File Header ******************************\
# File Name: Sources.inc for JPN KBDs
#
# Copyright (c) 1985-2000, Microsoft Corporation
#
# Project specific SOURCES file.
#
# History:
# May-14-1999 HiroYama Created
#***************************************************************************/

!include ..\..\fekbds.inc

C_DEFINES=$(C_DEFINES) -DJAPAN


INCLUDES=$(INCLUDES);..\inc

