
import "oaidl.idl";
import "ocidl.idl";

import "wudfddi.idl";

[
    uuid(EE383031-D737-45FD-BE5F-9A2EFE863627),
    version(1.0),
    helpstring("Windows Portable Device Multi-Transport Sample Driver Type Library")
]
library WpdMultiTransportDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(0CA6D3F4-9C49-4B81-BA8F-98F43AE6E592),
        helpstring("WpdMultiTransportDriver Class")
    ]
    coclass WpdMultiTransportDriver
    {
        [default] interface IDriverEntry;
    };
};

