//(C) COPYRIGHT MICROSOFT CORP., 1998-1999
#define IDI_TESTDEVICE                  2005

#define IDS_MESSAGEBOX_WIAUIEXTENSION_DIALOG        3001
#define IDS_MESSAGEBOX_WIAUIEXTENSION_TITLE         3002
#define IDS_MESSAGEBOX_TRANSFERMESSAGE_DIALOG       3003
