#pragma once
#define IDR_WpdWudfSampleDriver         101

#define IDR_WPD_SAMPLEDRIVER_IMAGE                  3000
#define IDR_WPD_SAMPLEDRIVER_IMAGE_THUMBNAIL        3001
#define IDR_WPD_SAMPLEDRIVER_MUSIC                  3002
#define IDR_WPD_SAMPLEDRIVER_DEVICE_ICON            3003
#define IDR_WPD_SAMPLEDRIVER_AUDIO_ANNOTATION       3004
#define IDR_WPD_SAMPLEDRIVER_VIDEO                  3005
#define IDR_WPD_SAMPLEDRIVER_CONTACT_PHOTO          3006
#define IDR_WPD_SAMPLEDRIVER_INTERNAL_STORAGE_ICON  3007
#define IDR_WPD_SAMPLEDRIVER_EXTERNAL_STORAGE_ICON  3008
#define IDR_WPD_SAMPLEDRIVER_MEMO                   3009
#define IDR_WPD_SAMPLEDRIVER_MEMO_ICON              3010
#define IDR_WPD_SAMPLEDRIVER_MEMO_FOLDER_ICON       3011

