
import "oaidl.idl";
import "ocidl.idl";

import "wudfddi.idl";

[
    uuid(780B0652-9672-42FF-9AEA-8AE2AE1AABE0),
    version(1.0),
    helpstring("WPD Sample Driver for new WUDF 1.0 Type Library")
]
library WpdWudfSampleDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(4F2FDA86-31DD-4840-A391-7A0F29220208),
        helpstring("WpdWudfSampleDriver Class")
    ]
    coclass WpdWudfSampleDriver
    {
        [default] interface IDriverEntry;
    };
};

