#define IDC_STATIC                      -1

#define IDD_SET_BUTTONS                 108
#define IDD_SET_SCALED_VALUE            109
#define IDD_SET_USAGE_VALUE             110
#define IDD_AUTOTEST_PARAMS             111
#define IDD_SET_USAGE_VALUE_ARRAY       112
#define IDD_USAGE_LIST_DIFFERENCE       113
#define IDD_UNSET_BUTTONS               114
#define IDD_UNSET_USAGES                115
#define IDD_SET_DATA                    116
#define IDD_SET_BUFFER_LENGTH           117
#define IDD_SET_INPUT_BUFFERS           118
#define IDD_GET_INDEX_STRING            119
#define IDD_SET_USAGES                  120
#define IDD_AUTOTEST_RESULTS            121
#define IDD_AUTOTEST_NEW                122
#define IDD_GET_EXT_ATTRIB              123
#define IDC_DEVICES                     1001
#define IDC_TYPE                        1002
#define IDC_ITEMS                       1003
#define IDC_ATTRIBUTES                  1004
#define IDC_READ                        1005
#define IDC_ABOUT                       1006
#define IDC_WRITE                       1007
#define IDC_EXTCALLS                    1008
#define IDC_SEND                        1100
#define ID_SEND                         1100
#define IDC_OUTPUT                      1101
#define IDC_EDIT1                       1102
#define IDC_USAGEPAGE                   1102
#define IDC_USAGE_LIST                  1102
#define IDC_STRING_INDEX                1102
#define IDC_LOGFILE                     1102
#define IDC_REPORTID                    1103
#define IDC_USAGE_LIST2                 1103
#define box                             1111
#define IDC_SCROLLBAR1                  1121
#define IDC_SCROLLBAR                   1121
#define IDC_INPUT                       1122
#define IDC_FEATURE                     1124
#define IDC_USAGE                       1126
#define IDC_LINKCOLL                    1127
#define IDC_CALLOUTPUT                  1128
#define IDC_EXECUTE                     1129
#define IDC_CANCEL                      1130
#define IDC_FEATURES                    1131
#define IDC_SET_PARAMS                  1131
#define IDC_REPORT_BUFFER               1132
#define IDC_INPUT_BUFFER                1132
#define IDC_BUFFER_TYPE                 1133
#define IDC_BUFFER_SIZE                 1134
#define IDC_INPUT_SELECT                1135
#define IDC_FEATURE_BUFFER              1136
#define IDC_USAGE_PAGE                  1136
#define IDC_FEATURE_SELECT              1137
#define IDC_OUTPUT_BUFFER               1138
#define IDC_VALUE                       1138
#define IDC_OUTPUT_SELECT               1139
#define IDC_INDEX                       1142
#define IDC_ADD_DATA                    1143
#define IDC_REMOVE_DATA                 1144
#define IDC_DATA_LIST                   1145
#define IDC_INPUT_BUFFERS               1147
#define IDC_BUFFER_LENGTH               1149
#define IDC_USAGE_LIST1                 1150
#define IDC_START_TESTS                 1151
#define IDC_LOAD_LOGICAL_DEVICE         1152
#define IDC_USELOG                      1152
#define IDC_INFINITE                    1153
#define IDC_PPD_ITS                     1154
#define IDC_STRESSLOG                   1154
#define IDC_RUN_PPD                     1155
#define IDC_RUN_CAPS                    1156
#define IDC_RUN_ATTRIB                  1157
#define IDC_RUN_STRINGS                 1158
#define IDC_RUN_GUID                    1159
#define IDC_ITERATIONS                  1160
#define IDC_CAPS_ITS                    1161
#define IDC_ATT_ITS                     1162
#define IDC_STR_ITS                     1163
#define IDC_GUID_ITS                    1164
#define IDC_TEST_ITS                    1165
#define IDC_RUN_BUFFERS                 1165
#define IDC_BUFFER_ITS                  1166
#define IDC_STOP_TESTS                  1167
#define IDC_RUN_GETFEATURE              1167
#define IDC_GETFEA_ITS                  1168
#define IDC_GETFEAT_ITS                 1168
#define IDC_LOGFILENAME                 1169
#define IDC_RUN_SETFEATURE              1169
#define IDC_SETFEA_ITS                  1170
#define IDC_TEST_RESULTS                1172
#define IDC_DEVICE_LIST                 1174
#define IDC_END_TESTS                   1175
#define IDC_READ_SYNCH                  1176
#define IDC_READ_ASYNCH_ONCE            1177
#define IDC_READ_ASYNCH                 1177
#define IDC_READ_ASYNCH_CONT            1178
#define IDC_RUN_LIST                    1178
#define IDC_NRUN_LIST                   1179
#define IDC_REMOVE_TEST                 1180
#define IDC_ADD_TEST                    1181
#define IDC_DESELECT_RUN                1182
#define IDC_SELECT_RUN                  1183
#define IDC_DESELECT_NRUN               1184
#define IDC_SELECT_NRUN                 1185
#define IDC_SET_ITERATIONS              1186
#define IDC_OUT_LABEL1                  2000
#define IDC_OUT_LABEL2                  2001
#define IDC_OUT_LABEL3                  2002
#define IDC_OUT_LABEL4                  2003
#define IDC_OUT_LABEL5                  2004
#define IDC_OUT_LABEL6                  2005
#define IDC_OUT_LABEL7                  2006
#define IDC_OUT_LABEL8                  2007
#define IDC_OUT_LABEL9                  2008
#define IDC_OUT_EDIT1                   3000
#define IDC_OUT_EDIT2                   3001
#define IDC_OUT_EDIT3                   3002
#define IDC_OUT_EDIT4                   3003
#define IDC_OUT_EDIT5                   3004
#define IDC_OUT_EDIT6                   3005
#define IDC_OUT_EDIT7                   3006
#define IDC_OUT_EDIT8                   3007
#define IDC_OUT_EDIT9                   3008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
