
import "oaidl.idl";
import "ocidl.idl";

import "wudfddi.idl";

[
    uuid(74FF6859-73D1-488C-B2EA-88BD6DA31A17),
    version(1.0),
    helpstring("Windows Portable Device Services Sample Driver Type Library")
]
library WpdServiceSampleDriverLib
{
    importlib("stdole2.tlb");
    [
        uuid(CFC0AF02-CE72-4717-83E7-D51BCFCBE87B),
        helpstring("WpdServiceSampleDriver Class")
    ]
    coclass WpdServiceSampleDriver
    {
        [default] interface IDriverEntry;
    };
};

